### ISSUE TITLE
AmplNLWriter: can't evaluate pow'(-1,1)

### ISSUE THREAD

**Issue by cbingane** [jump-dev/AmplNLWriter.jl#154] opened 2022-04-28 19:42 UTC
Hello,

I'm trying to solve the problem below with Couenne_jll using AmplNLWriter. However, I get this error message:

> Error evaluating "var =" definition -1: can't evaluate pow'(-1,1).

> ERROR: Result index of attribute MathOptInterface.ObjectiveValue(1) out of bounds. There are currently 0 solution(s) in the model.

The same code works fine when I use Ipopt with JuMP directly (i.e., without AmplNLWriter). It fails when I use Ipopt_jll with AmplNLWriter and I get the same error message. The issue seems to be with AmplNLWriter rather than the solver.

Could anyone please help with this?

Best regards,

Christian

```
function jump_max_perimeter_Bn(n)
    if mod(log2(n),1)==0 && n>=8
        d = pi/n - asin(sin(2*pi/n)/2);
        Ll = 2*n*sin(pi/(2*n))*cos(d/2);
        Lu = 2*n*sin(pi/(2*n));
        #model = Model(Ipopt.Optimizer)
        model = Model(() -> AmplNLWriter.Optimizer(Couenne_jll.amplexe))
        #model = Model(() -> AmplNLWriter.Optimizer("C:/Users/chris/couenne-win64/couenne.exe"))
        # Variables
        @variable(model, a[i = 1:Int(n/4+1)] >= 0, start = pi/n+(-1)^(i-1)*d)
        # Perimeter
        @NLobjective(model, Max, 4*sin(a[1]/2)+sum(8*sin(a[i]/2) for i in 2:Int(n/4))+4*sin(a[Int(n/4+1)]/2))
        # Diameter graph
        @constraint(model, a[1] + sum(2*a[k] for k in 2:Int(n/4)) + a[Int(n/4+1)] == pi/2)
        @NLconstraint(model, sin(a[1])+sum((-1)^(i-1)*sin(a[1]+
        sum(2*a[j] for j in 2:i)) for i in 2:Int(n/4)) == -1/2)
        @constraint(model, [i = 1:Int(n/4)], a[i] <= pi/6)
        @constraint(model, a[Int(n/4+1)] <= pi/3)
        # Bounds
        @NLconstraint(model, Ll <= 4*sin(a[1]/2)+sum(8*sin(a[i]/2) for i in 2:Int(n/4))+4*sin(a[Int(n/4+1)]/2) <= Lu)
        # Solving
        optimize!(model)
        L = objective_value(model)
        a = value.(a)
        ct = solve_time(model)
        return(L,a,ct)
    end
end
```

**Comment by odow** [comment] 2022-04-28 19:51
Before querying `value.(a)`, you must check if the solver found a solution. In this case, it looks like it didn't.

See:
https://jump.dev/JuMP.jl/stable/manual/solutions/#Solutions-summary
https://jump.dev/JuMP.jl/stable/manual/solutions/#Recommended-workflow

You'd have to look at the log to understand why the solver failed.

As a side note, don't use:
```julia
@constraint(model, [i = 1:Int(n/4)], a[i] <= pi/6)
@constraint(model, a[Int(n/4+1)] <= pi/3)
```
do
```Julia
set_upper_bound.(a, pi/6)
set_upper_bound(a[Int(n/4+1)], pi/3)
```
The former adds linear constraints, the latter adds variable bounds. Ipopt is more efficient at handling the latter.

**Comment by cbingane** [comment] 2022-04-28 20:25
Thank you @odow for your quick response. With the command `termination_status(model)`, I get

> OTHER_ERROR::TerminationStatusCode = 24

and the command `raw_status(model)` gives

> Error calling the solver. Failed with: ProcessFailedException(Base.Process[Process(`'C:\\Users\\chris\\.julia\\artifacts\\a193c7545d24bf6d69aa7f92ccfbe86bc05be3f6\\bin\\couenne.exe' 'C:\\Users\\chris\\AppData\\Local\\Temp\\jl_j2ymVK\\model.nl' -AMPL`, ProcessExited(1))])

```
n=8;
d = pi/n - asin(sin(2*pi/n)/2);
Ll = 2*n*sin(pi/(2*n))*cos(d/2);
Lu = 2*n*sin(pi/(2*n));
#model = Model(Ipopt.Optimizer)
model = Model(() -> AmplNLWriter.Optimizer(Couenne_jll.amplexe))
#model = Model(() -> AmplNLWriter.Optimizer("C:/Users/chris/couenne-win64/couenne.exe"))
# Variables
@variable(model, a[i = 1:Int(n/4+1)] >= 0, start = pi/n+(-1)^(i-1)*d)
# Perimeter
@NLobjective(model, Max, 4*sin(a[1]/2)+sum(8*sin(a[i]/2) for i in 2:Int(n/4))+4*sin(a[Int(n/4+1)]/2))
# Diameter graph
@constraint(model, a[1] + sum(2*a[k] for k in 2:Int(n/4)) + a[Int(n/4+1)] == pi/2)
@NLconstraint(model, sin(a[1])+sum((-1)^(i-1)*sin(a[1]+
sum(2*a[j] for j in 2:i)) for i in 2:Int(n/4)) == -1/2)
@constraint(model, [i = 1:Int(n/4)], a[i] <= pi/6)
@constraint(model, a[Int(n/4+1)] <= pi/3)
# Bounds
@NLconstraint(model, Ll <= 4*sin(a[1]/2)+sum(8*sin(a[i]/2) for i in 2:Int(n/4))+4*sin(a[Int(n/4+1)]/2) <= Lu)
# Solving
optimize!(model)
termination_status(model)
raw_status(model)
```

**Comment by odow** [comment] 2022-04-28 20:50
Ah. The problem is that Couenne doesn't know how to handle `-1^1`. So instead of
```julia
@NLconstraint(model, sin(a[1])+sum((-1)^(i-1)*sin(a[1]+ sum(2*a[j] for j in 2:i)) for i in 2:Int(n/4)) == -1/2)
```
do
```julia
coef = Dict(i => -1^(i-1) for i in 1:Int(n/4))
@NLconstraint(model, sin(a[1])+sum(coef[i]*sin(a[1]+ sum(2*a[j] for j in 2:i)) for i in 2:Int(n/4)) == -1/2)
```

**Comment by cbingane** [comment] 2022-04-28 21:03
Thank you so much @odow. I replaced (-1)^(i-1) by cos((i-1)*pi) and it worked.

However, the issue seems to be with AmplNLWriter rather than Couenne_jll. I got the same error with Ipopt_jll but the same code worked fine when I use Ipopt with JuMP directly (i.e., without AmplNLWriter).

Thanks again :)

**Comment by odow** [comment] 2022-07-08 02:32
I'm going to close this as expected behavior. It isn't a bug in AmplNLWriter.

**Closed by odow** 2022-07-08 02:32 UTC
Labels: question
